-- -----------------------------------------------------
-- Schema full-stack-STOCKS
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `nse-stocks`;

CREATE SCHEMA `nse-stocks`;
USE `nse-stocks` ;

-- -----------------------------------------------------
-- Table `full-stack-stocks`.`stock_sector`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nse-stocks`.`stock_sector` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `sector_name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE=InnoDB
AUTO_INCREMENT = 1;

-- -----------------------------------------------------
-- Table `full-stack-stocks`.`stock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nse-stocks`.`stock` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `sector_id` BIGINT(20) NOT NULL,
  `name` VARCHAR(255) DEFAULT NULL,
  `current_price` DECIMAL(13,2) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_category` (`sector_id`),
  CONSTRAINT `fk_sector` FOREIGN KEY (`sector_id`) REFERENCES `stock_sector` (`id`)
) 
ENGINE=InnoDB
AUTO_INCREMENT = 1;


-- -----------------------------------------------------
-- Add sample data
-- -----------------------------------------------------

INSERT INTO STOCK_SECTOR(SECTOR_NAME) VALUES ('AUTOMOBILE');
INSERT INTO STOCK_SECTOR(SECTOR_NAME) VALUES ('BANK');
INSERT INTO STOCK_SECTOR(SECTOR_NAME) VALUES ('CEMENTS');
INSERT INTO STOCK_SECTOR(SECTOR_NAME) VALUES ('CHEMICALS');
INSERT INTO STOCK_SECTOR(SECTOR_NAME) VALUES ('CONSTRUCTION');
INSERT INTO STOCK_SECTOR(SECTOR_NAME) VALUES ('CONSUMER GOODS');
INSERT INTO STOCK_SECTOR(SECTOR_NAME) VALUES ('ENERGY- OIL AND GAS');
INSERT INTO STOCK_SECTOR(SECTOR_NAME) VALUES ('ENERGY - POWER');
INSERT INTO STOCK_SECTOR(SECTOR_NAME) VALUES ('ENERGY AND MINING');
INSERT INTO STOCK_SECTOR(SECTOR_NAME) VALUES ('FINANCIAL SERVICES');
INSERT INTO STOCK_SECTOR(SECTOR_NAME) VALUES ('INFORMATION TECHNOLOGY');
INSERT INTO STOCK_SECTOR(SECTOR_NAME) VALUES ('INFRASTRUCTURE');
INSERT INTO STOCK_SECTOR(SECTOR_NAME) VALUES ('MEDIA AND ENTERTAINMENT');
INSERT INTO STOCK_SECTOR(SECTOR_NAME) VALUES ('METALS');
INSERT INTO STOCK_SECTOR(SECTOR_NAME) VALUES ('PHARMACEUTICALS');
INSERT INTO STOCK_SECTOR(SECTOR_NAME) VALUES ('TELECOMMUNICATION');

INSERT INTO STOCK (SECTOR_ID,NAME,CURRENT_PRICE)
VALUES (1,'BAJAJ AUTO',200.69);
INSERT INTO STOCK (SECTOR_ID,NAME,CURRENT_PRICE)
VALUES (1,'EICHER MOTORS',20789.29);
INSERT INTO STOCK (SECTOR_ID,NAME,CURRENT_PRICE)
VALUES (1,'HERO MOTOCORP',60.56);
INSERT INTO STOCK (SECTOR_ID,NAME,CURRENT_PRICE)
VALUES (1,'MAHINDRA AND MAHINDRA',80.00);
INSERT INTO STOCK (SECTOR_ID,NAME,CURRENT_PRICE)
VALUES (1,'MARUTI SUZUKI',300.00);
INSERT INTO STOCK (SECTOR_ID,NAME,CURRENT_PRICE)
VALUES (1,'TATA MOTORS',10.50);
INSERT INTO STOCK (SECTOR_ID,NAME,CURRENT_PRICE)
VALUES (2,'AXIS BANK',98.08);
INSERT INTO STOCK (SECTOR_ID,NAME,CURRENT_PRICE)
VALUES (2,'HDFC BANK',67.50);
INSERT INTO STOCK (SECTOR_ID,NAME,CURRENT_PRICE)
VALUES (2,'ICICI BANK',76.50);
INSERT INTO STOCK (SECTOR_ID,NAME,CURRENT_PRICE)
VALUES (2,'KOTAK MAHINDRA BANK',46.87);
INSERT INTO STOCK (SECTOR_ID,NAME,CURRENT_PRICE)
VALUES (2,'STATE BANK OF INDIA',10.50);
INSERT INTO STOCK (SECTOR_ID,NAME,CURRENT_PRICE)
VALUES (3,'GRASIM INDUSTRIES',98.08);
INSERT INTO STOCK (SECTOR_ID,NAME,CURRENT_PRICE)
VALUES (3,'SHREE CEMENTS',67.50);
INSERT INTO STOCK (SECTOR_ID,NAME,CURRENT_PRICE)
VALUES (3,'ULTRATECH CEMENT',76.50);
INSERT INTO STOCK (SECTOR_ID,NAME,CURRENT_PRICE)
VALUES (4,'UNITED PHOSPHORUS LIMITED',46.87);
INSERT INTO STOCK (SECTOR_ID,NAME,CURRENT_PRICE)
VALUES (5,'LARSEN AND TUBRO',10.50);
INSERT INTO STOCK (SECTOR_ID,NAME,CURRENT_PRICE)
VALUES (6,'ASIAN PAINTS',98.08);
INSERT INTO STOCK (SECTOR_ID,NAME,CURRENT_PRICE)
VALUES (6,'BRITANNIA INDUSTRIES',67.50);
INSERT INTO STOCK (SECTOR_ID,NAME,CURRENT_PRICE)
VALUES (6,'HINDUSTAN UNILEVER',76.50);
INSERT INTO STOCK (SECTOR_ID,NAME,CURRENT_PRICE)
VALUES (6,'ITC LIMITED',46.87);
INSERT INTO STOCK (SECTOR_ID,NAME,CURRENT_PRICE)
VALUES (6,'NESTLE INDIA',10.50);
INSERT INTO STOCK (SECTOR_ID,NAME,CURRENT_PRICE)
VALUES (6,'TITAN COMPANY',98.08);
INSERT INTO STOCK (SECTOR_ID,NAME,CURRENT_PRICE)
VALUES (7,'BHARAT PETROLEUM',67.50);
INSERT INTO STOCK (SECTOR_ID,NAME,CURRENT_PRICE)
VALUES (7,'GAIL',76.50);
INSERT INTO STOCK (SECTOR_ID,NAME,CURRENT_PRICE)
VALUES (7,'INDIAN OIL CORPORATION',46.87);
INSERT INTO STOCK (SECTOR_ID,NAME,CURRENT_PRICE)
VALUES (7,'OIL AND NATURAL GAS CORPORATION',10.50);
INSERT INTO STOCK (SECTOR_ID,NAME,CURRENT_PRICE)
VALUES (7,'RELIANCE INDUSTRIES',98.08);
INSERT INTO STOCK (SECTOR_ID,NAME,CURRENT_PRICE)
VALUES (8,'NTPC',67.50);
INSERT INTO STOCK (SECTOR_ID,NAME,CURRENT_PRICE)
VALUES (8,'POWER GRID CORPORATION OF INDIA',76.50);
INSERT INTO STOCK (SECTOR_ID,NAME,CURRENT_PRICE)
VALUES (9,'COAL INDIA',46.87);
