-- -----------------------------------------------------
-- Schema full-stack-STOCKS
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `nse-stocks`;

CREATE SCHEMA `nse-stocks`;
USE `nse-stocks` ;

-- -----------------------------------------------------
-- Table `full-stack-stocks`.`stock_sector`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nse-stocks`.`stock_sector` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `sector_name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE=InnoDB
AUTO_INCREMENT = 1;

-- -----------------------------------------------------
-- Table `full-stack-stocks`.`stock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nse-stocks`.`stock` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `sku` VARCHAR(255) DEFAULT NULL,
  `name` VARCHAR(255) DEFAULT NULL,
  `description` VARCHAR(255) DEFAULT NULL,
  `current_price` DECIMAL(13,2) DEFAULT NULL,
  `per_change` DECIMAL(13,2) DEFAULT NULL,
  `active` BIT DEFAULT 1,
  `qty` INT(11) DEFAULT NULL,
  `date_created` DATETIME(6) DEFAULT NULL,
  `last_updated` DATETIME(6) DEFAULT NULL,
  `sector_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_sector` (`sector_id`),
  CONSTRAINT `fk_sector` FOREIGN KEY (`sector_id`) REFERENCES `stock_sector` (`id`)
) 
ENGINE=InnoDB
AUTO_INCREMENT = 1;


-- -----------------------------------------------------
-- Add sample data
-- -----------------------------------------------------

INSERT INTO STOCK_SECTOR(SECTOR_NAME) VALUES ('AUTOMOBILE');
INSERT INTO STOCK_SECTOR(SECTOR_NAME) VALUES ('BANK');
INSERT INTO STOCK_SECTOR(SECTOR_NAME) VALUES ('CEMENTS');
INSERT INTO STOCK_SECTOR(SECTOR_NAME) VALUES ('CHEMICALS');
INSERT INTO STOCK_SECTOR(SECTOR_NAME) VALUES ('CONSTRUCTION');
INSERT INTO STOCK_SECTOR(SECTOR_NAME) VALUES ('CONSUMER GOODS');
INSERT INTO STOCK_SECTOR(SECTOR_NAME) VALUES ('ENERGY- OIL AND GAS');
INSERT INTO STOCK_SECTOR(SECTOR_NAME) VALUES ('ENERGY - POWER');
INSERT INTO STOCK_SECTOR(SECTOR_NAME) VALUES ('ENERGY AND MINING');
INSERT INTO STOCK_SECTOR(SECTOR_NAME) VALUES ('FINANCIAL SERVICES');
INSERT INTO STOCK_SECTOR(SECTOR_NAME) VALUES ('INFORMATION TECHNOLOGY');
INSERT INTO STOCK_SECTOR(SECTOR_NAME) VALUES ('INFRASTRUCTURE');
INSERT INTO STOCK_SECTOR(SECTOR_NAME) VALUES ('MEDIA AND ENTERTAINMENT');
INSERT INTO STOCK_SECTOR(SECTOR_NAME) VALUES ('METALS');
INSERT INTO STOCK_SECTOR(SECTOR_NAME) VALUES ('PHARMACEUTICALS');
INSERT INTO STOCK_SECTOR(SECTOR_NAME) VALUES ('TELECOMMUNICATION');

INSERT INTO STOCK (SKU,SECTOR_ID,NAME,DESCRIPTION,CURRENT_PRICE,PER_CHANGE,ACTIVE,DATE_CREATED)
VALUES ('BAJAJ-AUTO',1,'Bajaj Auto','Stocks of Bajaj Auto',3002.00,-0.99,1,now());
INSERT INTO STOCK (SKU,SECTOR_ID,NAME,DESCRIPTION,CURRENT_PRICE,PER_CHANGE,ACTIVE,DATE_CREATED)
VALUES ('EICHERMOT',1,'Eicher Motors','Stocks of Eicher Motors',20034.67,-1.50,1,now());
INSERT INTO STOCK (SKU,SECTOR_ID,NAME,DESCRIPTION,CURRENT_PRICE,PER_CHANGE,ACTIVE,DATE_CREATED)
VALUES ('HEROMOTOCO',1,'Hero MotoCorp','Stocks of Hero MotoCorp',754.93,-1.7,1,now());
INSERT INTO STOCK (SKU,SECTOR_ID,NAME,DESCRIPTION,CURRENT_PRICE,PER_CHANGE,ACTIVE,DATE_CREATED)
VALUES ('M&M',1,'Mahindra and Mahindra','Stocks of Mahindra and Mahindra',5498,0.99,1,now());
INSERT INTO STOCK (SKU,SECTOR_ID,NAME,DESCRIPTION,CURRENT_PRICE,PER_CHANGE,ACTIVE,DATE_CREATED)
VALUES ('MARUTI',1,'Maruti Suzuki','Stocks of Maruti Suzuki',300,-2.00,1,now());
INSERT INTO STOCK (SKU,SECTOR_ID,NAME,DESCRIPTION,CURRENT_PRICE,PER_CHANGE,ACTIVE,DATE_CREATED)
VALUES ('TATAMOTORS',1,'Tata Motors','Stocks of Tata Motors',156.00,-0.78,1,now());
INSERT INTO STOCK (SKU,SECTOR_ID,NAME,DESCRIPTION,CURRENT_PRICE,PER_CHANGE,ACTIVE,DATE_CREATED)
VALUES ('AXISBANK',2,'Axis Bank','Stocks of Axis Bank',373.00,-0.99,1,now());
INSERT INTO STOCK (SKU,SECTOR_ID,NAME,DESCRIPTION,CURRENT_PRICE,PER_CHANGE,ACTIVE,DATE_CREATED)
VALUES ('HDFCBANK',2,'HDFC Bank','Stocks of HDFC Bank',30.89,-0.99,1,now());
INSERT INTO STOCK (SKU,SECTOR_ID,NAME,DESCRIPTION,CURRENT_PRICE,PER_CHANGE,ACTIVE,DATE_CREATED)
VALUES ('ICICIBANK',2,'ICICI Bank','Stocks of ICICI Bank',302.09,1.76,1,now());
INSERT INTO STOCK (SKU,SECTOR_ID,NAME,DESCRIPTION,CURRENT_PRICE,PER_CHANGE,ACTIVE,DATE_CREATED)
VALUES ('INDUSINDBANK',2,'IndusInd Bank','Stocks of IndusInd Bank',398.00,-0.89,1,now());
INSERT INTO STOCK (SKU,SECTOR_ID,NAME,DESCRIPTION,CURRENT_PRICE,PER_CHANGE,ACTIVE,DATE_CREATED)
VALUES ('KOTAKBANK',2,'Kotak Mahindra Bank','Stocks of Kotak Mahindra Bank',3002.00,-0.99,1,now());
INSERT INTO STOCK (SKU,SECTOR_ID,NAME,DESCRIPTION,CURRENT_PRICE,PER_CHANGE,ACTIVE,DATE_CREATED)
VALUES ('SBIN',2,'State Bank of India','Stocks of State Bank of India',20034.67,-1.50,1,now());
INSERT INTO STOCK (SKU,SECTOR_ID,NAME,DESCRIPTION,CURRENT_PRICE,PER_CHANGE,ACTIVE,DATE_CREATED)
VALUES ('GRASIM',3,'Grasim Industries','Stocks of Grasim Industries',754.93,-1.7,1,now());
INSERT INTO STOCK (SKU,SECTOR_ID,NAME,DESCRIPTION,CURRENT_PRICE,PER_CHANGE,ACTIVE,DATE_CREATED)
VALUES ('SHREECEM',3,'Shree Cements','Stocks of Shree Cements',3002.00,-0.99,1,now());
INSERT INTO STOCK (SKU,SECTOR_ID,NAME,DESCRIPTION,CURRENT_PRICE,PER_CHANGE,ACTIVE,DATE_CREATED)
VALUES ('ULTRACEMCO',3,'UltraTech Cement','Stocks of UltraTech Cement',3002.00,-0.99,1,now());
INSERT INTO STOCK (SKU,SECTOR_ID,NAME,DESCRIPTION,CURRENT_PRICE,PER_CHANGE,ACTIVE,DATE_CREATED)
VALUES ('UPL',4,'United Phosphorous Limited','Stocks of United Phosphorous Limited',3002.00,-0.99,1,now());
INSERT INTO STOCK (SKU,SECTOR_ID,NAME,DESCRIPTION,CURRENT_PRICE,PER_CHANGE,ACTIVE,DATE_CREATED)
VALUES ('LT',5,'Larsen and Toubro','Stocks of Larsen and Toubro',3002.00,-0.99,1,now());
INSERT INTO STOCK (SKU,SECTOR_ID,NAME,DESCRIPTION,CURRENT_PRICE,PER_CHANGE,ACTIVE,DATE_CREATED)
VALUES ('ASIANPAINT',6,'Asian Paints','Stocks of Asian Paints',3002.00,-0.99,1,now());
INSERT INTO STOCK (SKU,SECTOR_ID,NAME,DESCRIPTION,CURRENT_PRICE,PER_CHANGE,ACTIVE,DATE_CREATED)
VALUES ('BRITANNIA',6,'Britannia Industries','Stocks of Britannia Industries',3002.00,-0.99,1,now());
INSERT INTO STOCK (SKU,SECTOR_ID,NAME,DESCRIPTION,CURRENT_PRICE,PER_CHANGE,ACTIVE,DATE_CREATED)
VALUES ('HINDUNILVR',6,'Hindustan Unilever','Stocks of Hindustan Unilever',3002.00,-0.99,1,now());
INSERT INTO STOCK (SKU,SECTOR_ID,NAME,DESCRIPTION,CURRENT_PRICE,PER_CHANGE,ACTIVE,DATE_CREATED)
VALUES ('ITC',6,'ITC Limited','Stocks of ITC Limited',3002.00,-0.99,1,now());
INSERT INTO STOCK (SKU,SECTOR_ID,NAME,DESCRIPTION,CURRENT_PRICE,PER_CHANGE,ACTIVE,DATE_CREATED)
VALUES ('NESTLEIND',6,'Nestle India','Stocks of Nestle India',20034.67,-1.50,1,now());
INSERT INTO STOCK (SKU,SECTOR_ID,NAME,DESCRIPTION,CURRENT_PRICE,PER_CHANGE,ACTIVE,DATE_CREATED)
VALUES ('TITAN',6,'Titan Company','Stocks of Titan Company',754.93,-1.7,1,now());
INSERT INTO STOCK (SKU,SECTOR_ID,NAME,DESCRIPTION,CURRENT_PRICE,PER_CHANGE,ACTIVE,DATE_CREATED)
VALUES ('BPCL',7,'Bharat Petroleum','Stocks of Bajaj Auto',3002.00,-0.99,1,now());
INSERT INTO STOCK (SKU,SECTOR_ID,NAME,DESCRIPTION,CURRENT_PRICE,PER_CHANGE,ACTIVE,DATE_CREATED)
VALUES ('GAIL',7,'GAIL','Stocks of GAIL',3002.00,-0.99,1,now());
INSERT INTO STOCK (SKU,SECTOR_ID,NAME,DESCRIPTION,CURRENT_PRICE,PER_CHANGE,ACTIVE,DATE_CREATED)
VALUES ('IOC',7,'Indian Oil Corporation','Stocks of Indian Oil Corporation',3002.00,-0.99,1,now());
INSERT INTO STOCK (SKU,SECTOR_ID,NAME,DESCRIPTION,CURRENT_PRICE,PER_CHANGE,ACTIVE,DATE_CREATED)
VALUES ('ONGC',7,'Oil and Natural Gas Corporation','Stocks of Oil and Natural Gas Corporation',3002.00,-0.99,1,now());
INSERT INTO STOCK (SKU,SECTOR_ID,NAME,DESCRIPTION,CURRENT_PRICE,PER_CHANGE,ACTIVE,DATE_CREATED)
VALUES ('RELIANCE',7,'Reliance Industries','Stocks of Reliance Industries',3002.00,-0.99,1,now());
INSERT INTO STOCK (SKU,SECTOR_ID,NAME,DESCRIPTION,CURRENT_PRICE,PER_CHANGE,ACTIVE,DATE_CREATED)
VALUES ('NTPC',8,'NTPC','Stocks of NTPC',3002.00,-0.99,1,now());
INSERT INTO STOCK (SKU,SECTOR_ID,NAME,DESCRIPTION,CURRENT_PRICE,PER_CHANGE,ACTIVE,DATE_CREATED)
VALUES ('POWERGRID',8,'PowerGrid Corporation Of Inida','Stocks of PowerGrid Corporation Of Inida',3002.00,-0.99,1,now());
INSERT INTO STOCK (SKU,SECTOR_ID,NAME,DESCRIPTION,CURRENT_PRICE,PER_CHANGE,ACTIVE,DATE_CREATED)
VALUES ('COALINDIA',9,'Coal India','Stocks of Coal India',3002.00,-0.99,1,now());
INSERT INTO STOCK (SKU,SECTOR_ID,NAME,DESCRIPTION,CURRENT_PRICE,PER_CHANGE,ACTIVE,DATE_CREATED)
VALUES ('BAJFINANCE',10,'Bajaj Finance','Stocks of Bajaj Finance',20034.67,-1.50,1,now());
INSERT INTO STOCK (SKU,SECTOR_ID,NAME,DESCRIPTION,CURRENT_PRICE,PER_CHANGE,ACTIVE,DATE_CREATED)
VALUES ('BAJAJFINSV',10,'Bajaj Finserv','Stocks of Bajaj Finserv',754.93,-1.7,1,now());
INSERT INTO STOCK (SKU,SECTOR_ID,NAME,DESCRIPTION,CURRENT_PRICE,PER_CHANGE,ACTIVE,DATE_CREATED)
VALUES ('HDFC',10,'HDFC','Stocks of HDFC',3002.00,-0.99,1,now());
INSERT INTO STOCK (SKU,SECTOR_ID,NAME,DESCRIPTION,CURRENT_PRICE,PER_CHANGE,ACTIVE,DATE_CREATED)
VALUES ('HCLTECH',11,'HCL Technologies','Stocks of HCL Technologies',3002.00,-0.99,1,now());
INSERT INTO STOCK (SKU,SECTOR_ID,NAME,DESCRIPTION,CURRENT_PRICE,PER_CHANGE,ACTIVE,DATE_CREATED)
VALUES ('INFY',11,'Infosys','Stocks of Infosys',3002.00,-0.99,1,now());
INSERT INTO STOCK (SKU,SECTOR_ID,NAME,DESCRIPTION,CURRENT_PRICE,PER_CHANGE,ACTIVE,DATE_CREATED)
VALUES ('TCS',11,'Tata Consultancy Services','Stocks of Tata Consultancy Services',3002.00,-0.99,1,now());
INSERT INTO STOCK (SKU,SECTOR_ID,NAME,DESCRIPTION,CURRENT_PRICE,PER_CHANGE,ACTIVE,DATE_CREATED)
VALUES ('TECHM',11,'Tech Mahindra','Stocks of Tech Mahindra',3002.00,-0.99,1,now());
INSERT INTO STOCK (SKU,SECTOR_ID,NAME,DESCRIPTION,CURRENT_PRICE,PER_CHANGE,ACTIVE,DATE_CREATED)
VALUES ('WIPRO',11,'Wipro','Stocks of WIpro Technologies',3002.00,-0.99,1,now());
INSERT INTO STOCK (SKU,SECTOR_ID,NAME,DESCRIPTION,CURRENT_PRICE,PER_CHANGE,ACTIVE,DATE_CREATED)
VALUES ('ADANIPORTS',12,'Adani Ports','Stocks of Adani Ports',3002.00,-0.99,1,now());
INSERT INTO STOCK (SKU,SECTOR_ID,NAME,DESCRIPTION,CURRENT_PRICE,PER_CHANGE,ACTIVE,DATE_CREATED)
VALUES ('ZEEL',13,'Zee Entertainment Enterprises','Stocks of Zee Entertainment Enterprises',3002.00,-0.99,1,now());
INSERT INTO STOCK (SKU,SECTOR_ID,NAME,DESCRIPTION,CURRENT_PRICE,PER_CHANGE,ACTIVE,DATE_CREATED)
VALUES ('HINDALCO',14,'HindalCo Industries','Stocks of HindalCo Industries',20034.67,-1.50,1,now());
INSERT INTO STOCK (SKU,SECTOR_ID,NAME,DESCRIPTION,CURRENT_PRICE,PER_CHANGE,ACTIVE,DATE_CREATED)
VALUES ('JSWSTEEL',14,'JSW Steel','Stocks of JSW Steel',754.93,-1.7,1,now());
INSERT INTO STOCK (SKU,SECTOR_ID,NAME,DESCRIPTION,CURRENT_PRICE,PER_CHANGE,ACTIVE,DATE_CREATED)
VALUES ('TATASTEEL',14,'TATA Steel','Stocks of TATA Steel',3002.00,-0.99,1,now());
INSERT INTO STOCK (SKU,SECTOR_ID,NAME,DESCRIPTION,CURRENT_PRICE,PER_CHANGE,ACTIVE,DATE_CREATED)
VALUES ('VEDL',14,'Vedanta ','Stocks of Vedanta',3002.00,-0.99,1,now());
INSERT INTO STOCK (SKU,SECTOR_ID,NAME,DESCRIPTION,CURRENT_PRICE,PER_CHANGE,ACTIVE,DATE_CREATED)
VALUES ('CIPLA',15,'Cipla','Stocks of Cipla',3002.00,-0.99,1,now());
INSERT INTO STOCK (SKU,SECTOR_ID,NAME,DESCRIPTION,CURRENT_PRICE,PER_CHANGE,ACTIVE,DATE_CREATED)
VALUES ('DRREDDY',15,'Dr. Reddys Laboratory','Stocks of Dr. Reddys Laboratory',3002.00,-0.99,1,now());
INSERT INTO STOCK (SKU,SECTOR_ID,NAME,DESCRIPTION,CURRENT_PRICE,PER_CHANGE,ACTIVE,DATE_CREATED)
VALUES ('SUNPHARMA',15,'Sun Pharmaceuticals','Stocks of Sun Pharmaceuticals',3002.00,-0.99,1,now());
INSERT INTO STOCK (SKU,SECTOR_ID,NAME,DESCRIPTION,CURRENT_PRICE,PER_CHANGE,ACTIVE,DATE_CREATED)
VALUES ('BHARTIARTL',16,'Bharati Airtel','Stocks of Bharati Airtel',3002.00,-0.99,1,now());
INSERT INTO STOCK (SKU,SECTOR_ID,NAME,DESCRIPTION,CURRENT_PRICE,PER_CHANGE,ACTIVE,DATE_CREATED)
VALUES ('INFRATEL',16,'Bharati Infratel','Stocks of Bharati Infratel',3002.00,-0.99,1,now());
