-- -----------------------------------------------------
-- Schema full-stack-STOCKS
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `nse-stocks`;

CREATE SCHEMA `nse-stocks`;
USE `nse-stocks` ;

-- -----------------------------------------------------
-- Table `full-stack-stocks`.`stock_sector`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nse-stocks`.`stock_sector` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `sector_name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE=InnoDB
AUTO_INCREMENT = 1;

-- -----------------------------------------------------
-- Table `full-stack-stocks`.`stock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nse-stocks`.`stock` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `sector_id` BIGINT(20) NOT NULL,
  `name` VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_category` (`sector_id`),
  CONSTRAINT `fk_sector` FOREIGN KEY (`sector_id`) REFERENCES `sector` (`id`)
) 
ENGINE=InnoDB
AUTO_INCREMENT = 1;


-- -----------------------------------------------------
-- Add sample data
-- -----------------------------------------------------

INSERT INTO STOCK_SECTOR(SECTOR_NAME) VALUES ('AUTOMOBILE');
INSERT INTO STOCK_SECTOR(SECTOR_NAME) VALUES ('BANK');
INSERT INTO STOCK_SECTOR(SECTOR_NAME) VALUES ('CEMENTS');
INSERT INTO STOCK_SECTOR(SECTOR_NAME) VALUES ('CHEMICALS');
INSERT INTO STOCK_SECTOR(SECTOR_NAME) VALUES ('CONSTRUCTION');
INSERT INTO STOCK_SECTOR(SECTOR_NAME) VALUES ('CONSUMER GOODS');
INSERT INTO STOCK_SECTOR(SECTOR_NAME) VALUES ('ENERGY- OIL AND GAS');
INSERT INTO STOCK_SECTOR(SECTOR_NAME) VALUES ('ENERGY - POWER');
INSERT INTO STOCK_SECTOR(SECTOR_NAME) VALUES ('ENERGY AND MINING');
INSERT INTO STOCK_SECTOR(SECTOR_NAME) VALUES ('FINANCIAL SERVICES');
INSERT INTO STOCK_SECTOR(SECTOR_NAME) VALUES ('INFORMATION TECHNOLOGY');
INSERT INTO STOCK_SECTOR(SECTOR_NAME) VALUES ('INFRASTRUCTURE');
INSERT INTO STOCK_SECTOR(SECTOR_NAME) VALUES ('MEDIA AND ENTERTAINMENT');
INSERT INTO STOCK_SECTOR(SECTOR_NAME) VALUES ('METALS');
INSERT INTO STOCK_SECTOR(SECTOR_NAME) VALUES ('PHARMACEUTICALS');
INSERT INTO STOCK_SECTOR(SECTOR_NAME) VALUES ('TELECOMMUNICATION');

INSERT INTO STOCK (SECTOR_ID,NAME)
VALUES (1,'BAJAJ AUTO');
INSERT INTO STOCK (SECTOR_ID,NAME)
VALUES (1,'EICHER MOTORS');
INSERT INTO STOCK (SECTOR_ID,NAME)
VALUES (1,'HERO MOTOCORP');
INSERT INTO STOCK (SECTOR_ID,NAME)
VALUES (1,'MAHINDRA AND MAHINDRA');
INSERT INTO STOCK (SECTOR_ID,NAME)
VALUES (1,'MARUTI SUZUKI');
INSERT INTO STOCK (SECTOR_ID,NAME)
VALUES (1,'TATA MOTORS');
INSERT INTO STOCK (SECTOR_ID,NAME)
VALUES (2,'AXIS BANK');
INSERT INTO STOCK (SECTOR_ID,NAME)
VALUES (2,'HDFC BANK');
INSERT INTO STOCK (SECTOR_ID,NAME)
VALUES (2,'ICICI BANK');
INSERT INTO STOCK (SECTOR_ID,NAME)
VALUES (2,'INDUSIND BANK');
